name: bflutter_poc
description: BeeSightSoft Flutter Core Proof of concept
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  bflutter:
    git:
      url: git://github.com/beesightsoft/bflutter
      path: bflutter

  http: ^0.12.0+2
  flutter_spinkit: ^4.0.0
  connectivity: ^0.4.5+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.7.1

flutter_icons:
  image_path: "assets/icons/app_icon.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  image_path_android: "assets/icons/app_icon.png"
  image_path_ios: "assets/icons/app_icon.png"
  adaptive_icon_background: "assets/icons/app_icon.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/icons/app_icon.png" # only available for Android 8.0 devices and above

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

  fonts:
    - family: SF-Pro-Text-Black
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Black.otf

    - family: SF-Pro-Text-Bold
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Bold.otf

    - family: SF-Pro-Text-Heavy
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Heavy.otf

    - family: SF-Pro-Text-Light
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Light.otf

    - family: SF-Pro-Text-Medium
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Medium.otf

    - family: SF-Pro-Text-Regular
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Regular.otf

    - family: SF-Pro-Text-Semibold
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf

    - family: SF-Pro-Text-Thin
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Thin.otf

dependency_overrides:
  bflutter:
    path: ../