name: bflutter
description: BeeSight Soft Flutter core package, bloc, caching, auth, network, lifecycle, utils
version: 0.1.8+4
homepage: https://github.com/beesightsoft/bflutter

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart:
  sqflite:
  path:
  uuid:
  flutter_spinkit:
  connectivity:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

